apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aad-pod-identity
  namespace: flux-system
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-config
    namespace: flux-system
  validation: none
  path: ./apps/aad-pod-identity/${ENVIRONMENT}
  postBuild:
    substitute:
      NAMESPACE: "aad-pod-identity"
      CLUSTER_FULL_NAME: "${ENVIRONMENT}-${CLUSTER}"
