apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: azure-vote-backend
  annotations:
    hmcts.github.com/prod-automated: disabled
spec:
  filterTags:
    pattern: '^prod'
    extract: ''
  policy:
    alphabetical:
      order: asc
  imageRepositoryRef:
    name: azure-vote-backend
