apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: azure-vote-backend
  hmcts.github.com/image-registry: hmctsprivate
spec:
  image: thomasacracr.azurecr.io/azure-vote-backend
