apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: credentials-sync  # name must match the stub-resource in az-identity.yaml
  namespace: flux-system
spec:
  clientID: b1db54c3-0cfa-4fa9-891b-f8299ec0731e
  resourceID: /subscriptions/04109105-f3ca-44ac-a3a7-66b4936112c3/resourceGroups/thomas-vnet-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/acr-mi-test
  type: 0  # user-managed identity